Classification Models


*   K-nearest neighbors

In [1]:
# Import Modules

import pandas as pd
import os

from warnings import simplefilter
simplefilter(action='ignore', category=FutureWarning)
from pathlib import Path
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.preprocessing import StandardScaler

# Display all of the columns
pd.set_option('display.max_columns', None)

In [2]:
#mount drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
#Read the CSV file into a Pandas DataFrame
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Proj4/train.csv")
df

,ID,CustomerID,Month,Name,Age,SSN,Occupation,AnnualIncome,MonthlyInhandSalary,NumBankAccounts,NumCreditCard,InterestRate,NumofLoan,TypeofLoan,Delayfromduedate,NumofDelayedPayment,ChangedCreditLimit,NumCreditInquiries,CreditMix,OutstandingDebt,CreditUtilizationRatio,CreditHistoryAge,PaymentofMinAmount,TotalEMIpermonth,Amountinvestedmonthly,PaymentBehaviour,MonthlyBalance,CreditScore
0,0x1602,CUS0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,7.0,11.27,4.0,NaN,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.415295,HighspentSmallvaluepayments,312.494089,Good
1,0x1603,CUS0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,NaN,11.27,4.0,Good,809.98,31.944960,NaN,No,49.574949,118.280222,LowspentLargevaluepayments,284.629162,Good
2,0x1604,CUS0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,7.0,NaN,4.0,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521,LowspentMediumvaluepayments,331.209863,Good
3,0x1605,CUS0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,4.0,6.27,4.0,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.458074,LowspentSmallvaluepayments,223.451310,Good
4,0x1606,CUS0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,NaN,11.27,4.0,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153,HighspentMediumvaluepayments,341.489231,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,0x25fe9,CUS0x942c,April,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",23,7.0,11.50,3.0,NaN,502.38,34.663572,31 Years and 6 Months,No,35.104023,60.971333,HighspentLargevaluepayments,479.866228,Poor
99996,0x25fea,CUS0x942c,May,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",18,7.0,11.50,3.0,NaN,502.38,40.565631,31 Years and 7 Months,No,35.104023,54.185950,HighspentMediumvaluepayments,496.651610,Poor
99997,0x25feb,CUS0x942c,June,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,6,5729,2,"Auto Loan, and Student Loan",27,6.0,11.50,3.0,Good,502.38,41.255522,31 Years and 8 Months,No,35.104023,24.028477,HighspentLargevaluepayments,516.809083,Poor
99998,0x25fec,CUS0x942c,July,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",20,NaN,11.50,3.0,Good,502.38,33.638208,31 Years and 9 Months,No,35.104023,251.672582,LowspentLargevaluepayments,319.164979,Standard
99999,0x25fed,CUS0x942c,August,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",18,6.0,11.50,3.0,Good,502.38,34.192463,31 Years and 10 Months,No,35.104023,167.163865,!@9#%8,393.673696,Poor

In [4]:
#Data cleaning
#Drop unnecessary columns
columns_to_drop = ["ID", "CustomerID", "Month", "Name", "Age",
                   "SSN", "Occupation", "TypeofLoan", "InterestRate", "ChangedCreditLimit","MonthlyInhandSalary",
                   "PaymentofMinAmount", "TotalEMIpermonth", "Amountinvestedmonthly",
                   "PaymentBehaviour"]
cleandf = df.drop(columns = columns_to_drop)
cleandf

,AnnualIncome,NumBankAccounts,NumCreditCard,NumofLoan,Delayfromduedate,NumofDelayedPayment,NumCreditInquiries,CreditMix,OutstandingDebt,CreditUtilizationRatio,CreditHistoryAge,MonthlyBalance,CreditScore
0,19114.12,3,4,4,3,7.0,4.0,NaN,809.98,26.822620,22 Years and 1 Months,312.494089,Good
1,19114.12,3,4,4,-1,NaN,4.0,Good,809.98,31.944960,NaN,284.629162,Good
2,19114.12,3,4,4,3,7.0,4.0,Good,809.98,28.609352,22 Years and 3 Months,331.209863,Good
3,19114.12,3,4,4,5,4.0,4.0,Good,809.98,31.377862,22 Years and 4 Months,223.451310,Good
4,19114.12,3,4,4,6,NaN,4.0,Good,809.98,24.797347,22 Years and 5 Months,341.489231,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,39628.99,4,6,2,23,7.0,3.0,NaN,502.38,34.663572,31 Years and 6 Months,479.866228,Poor
99996,39628.99,4,6,2,18,7.0,3.0,NaN,502.38,40.565631,31 Years and 7 Months,496.651610,Poor
99997,39628.99,4,6,2,27,6.0,3.0,Good,502.38,41.255522,31 Years and 8 Months,516.809083,Poor
99998,39628.99,4,6,2,20,NaN,3.0,Good,502.38,33.638208,31 Years and 9 Months,319.164979,Standard
99999,39628.99,4,6,2,18,6.0,3.0,Good,502.38,34.192463,31 Years and 10 Months,393.673696,Poor

In [5]:
#Convert CreditHistoryAge string data value to usable form by extracting numerical part
cleandf['CreditHistoryAge'] = cleandf['CreditHistoryAge'].str[:2]
cleandf

,AnnualIncome,NumBankAccounts,NumCreditCard,NumofLoan,Delayfromduedate,NumofDelayedPayment,NumCreditInquiries,CreditMix,OutstandingDebt,CreditUtilizationRatio,CreditHistoryAge,MonthlyBalance,CreditScore
0,19114.12,3,4,4,3,7.0,4.0,NaN,809.98,26.822620,22,312.494089,Good
1,19114.12,3,4,4,-1,NaN,4.0,Good,809.98,31.944960,NaN,284.629162,Good
2,19114.12,3,4,4,3,7.0,4.0,Good,809.98,28.609352,22,331.209863,Good
3,19114.12,3,4,4,5,4.0,4.0,Good,809.98,31.377862,22,223.451310,Good
4,19114.12,3,4,4,6,NaN,4.0,Good,809.98,24.797347,22,341.489231,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,39628.99,4,6,2,23,7.0,3.0,NaN,502.38,34.663572,31,479.866228,Poor
99996,39628.99,4,6,2,18,7.0,3.0,NaN,502.38,40.565631,31,496.651610,Poor
99997,39628.99,4,6,2,27,6.0,3.0,Good,502.38,41.255522,31,516.809083,Poor
99998,39628.99,4,6,2,20,NaN,3.0,Good,502.38,33.638208,31,319.164979,Standard
99999,39628.99,4,6,2,18,6.0,3.0,Good,502.38,34.192463,31,393.673696,Poor

In [6]:
#Drop Creditmix rows with blank
cleandf = cleandf.dropna(subset=['CreditMix'])

In [7]:
#Converting String to Int
cleandf['CreditHistoryAge'] = pd.to_numeric(cleandf['CreditHistoryAge'], errors='coerce')

<ipython-input-7-eaa9c2e3ab18>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleandf['CreditHistoryAge'] = pd.to_numeric(cleandf['CreditHistoryAge'], errors='coerce')

In [8]:
#Binning Target Column
bin_mapping = {
    'Good': 'Good/Standard',
    'Standard': 'Good/Standard',
    'Poor': 'Poor'
}

# Create a new column for the binned categories
cleandf['target'] = cleandf['CreditScore'].map(bin_mapping)
cleandf = cleandf.drop(columns = 'CreditScore')
cleandf

<ipython-input-8-fea20cf58aab>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleandf['target'] = cleandf['CreditScore'].map(bin_mapping)

,AnnualIncome,NumBankAccounts,NumCreditCard,NumofLoan,Delayfromduedate,NumofDelayedPayment,NumCreditInquiries,CreditMix,OutstandingDebt,CreditUtilizationRatio,CreditHistoryAge,MonthlyBalance,target
1,19114.12,3,4,4,-1,NaN,4.0,Good,809.98,31.944960,NaN,284.629162,Good/Standard
2,19114.12,3,4,4,3,7.0,4.0,Good,809.98,28.609352,22.0,331.209863,Good/Standard
3,19114.12,3,4,4,5,4.0,4.0,Good,809.98,31.377862,22.0,223.451310,Good/Standard
4,19114.12,3,4,4,6,NaN,4.0,Good,809.98,24.797347,22.0,341.489231,Good/Standard
5,19114.12,3,4,4,8,4.0,4.0,Good,809.98,27.262259,22.0,340.479212,Good/Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,20002.88,10,8,5,33,25.0,9.0,Bad,3571.70,37.140784,6.0,337.362988,Good/Standard
99993,39628.99,4,6,2,23,NaN,3.0,Good,502.38,29.135447,31.0,400.104466,Good/Standard
99997,39628.99,4,6,2,27,6.0,3.0,Good,502.38,41.255522,31.0,516.809083,Poor
99998,39628.99,4,6,2,20,NaN,3.0,Good,502.38,33.638208,31.0,319.164979,Good/Standard
99999,39628.99,4,6,2,18,6.0,3.0,Good,502.38,34.192463,31.0,393.673696,Poor

In [9]:
#Check Datatypes
cleandf.dtypes

AnnualIncome              float64
NumBankAccounts             int64
NumCreditCard               int64
NumofLoan                   int64
Delayfromduedate            int64
NumofDelayedPayment       float64
NumCreditInquiries        float64
CreditMix                  object
OutstandingDebt           float64
CreditUtilizationRatio    float64
CreditHistoryAge          float64
MonthlyBalance            float64
target                     object
dtype: object

In [10]:
#Fill in blank field with zeros
cleandf = cleandf.fillna(0)
cleandf

,AnnualIncome,NumBankAccounts,NumCreditCard,NumofLoan,Delayfromduedate,NumofDelayedPayment,NumCreditInquiries,CreditMix,OutstandingDebt,CreditUtilizationRatio,CreditHistoryAge,MonthlyBalance,target
1,19114.12,3,4,4,-1,0.0,4.0,Good,809.98,31.944960,0.0,284.629162,Good/Standard
2,19114.12,3,4,4,3,7.0,4.0,Good,809.98,28.609352,22.0,331.209863,Good/Standard
3,19114.12,3,4,4,5,4.0,4.0,Good,809.98,31.377862,22.0,223.451310,Good/Standard
4,19114.12,3,4,4,6,0.0,4.0,Good,809.98,24.797347,22.0,341.489231,Good/Standard
5,19114.12,3,4,4,8,4.0,4.0,Good,809.98,27.262259,22.0,340.479212,Good/Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,20002.88,10,8,5,33,25.0,9.0,Bad,3571.70,37.140784,6.0,337.362988,Good/Standard
99993,39628.99,4,6,2,23,0.0,3.0,Good,502.38,29.135447,31.0,400.104466,Good/Standard
99997,39628.99,4,6,2,27,6.0,3.0,Good,502.38,41.255522,31.0,516.809083,Poor
99998,39628.99,4,6,2,20,0.0,3.0,Good,502.38,33.638208,31.0,319.164979,Good/Standard
99999,39628.99,4,6,2,18,6.0,3.0,Good,502.38,34.192463,31.0,393.673696,Poor

In [11]:
#Export clean data to csv
csvpath = "/content/drive/MyDrive/Colab Notebooks/Proj4/traincleanresult.csv"
cleandf.to_csv(csvpath, index=False)

In [12]:
#Check data types
cleandf.dtypes

AnnualIncome              float64
NumBankAccounts             int64
NumCreditCard               int64
NumofLoan                   int64
Delayfromduedate            int64
NumofDelayedPayment       float64
NumCreditInquiries        float64
CreditMix                  object
OutstandingDebt           float64
CreditUtilizationRatio    float64
CreditHistoryAge          float64
MonthlyBalance            float64
target                     object
dtype: object

In [13]:
# Split target column from dataset
y = cleandf['target']
X= cleandf.drop(columns='target')

In [14]:
# Preview the data
X[:8]

,AnnualIncome,NumBankAccounts,NumCreditCard,NumofLoan,Delayfromduedate,NumofDelayedPayment,NumCreditInquiries,CreditMix,OutstandingDebt,CreditUtilizationRatio,CreditHistoryAge,MonthlyBalance
1,19114.12,3,4,4,-1,0.0,4.0,Good,809.98,31.944960,0.0,284.629162
2,19114.12,3,4,4,3,7.0,4.0,Good,809.98,28.609352,22.0,331.209863
3,19114.12,3,4,4,5,4.0,4.0,Good,809.98,31.377862,22.0,223.451310
4,19114.12,3,4,4,6,0.0,4.0,Good,809.98,24.797347,22.0,341.489231
5,19114.12,3,4,4,8,4.0,4.0,Good,809.98,27.262259,22.0,340.479212
6,19114.12,3,4,4,3,8.0,4.0,Good,809.98,22.537593,22.0,244.565317
7,19114.12,3,4,4,3,6.0,4.0,Good,809.98,23.933795,0.0,358.124168
8,34847.84,2,4,1,3,4.0,2.0,Good,605.03,24.464031,26.0,470.690627

In [15]:
# Print first ten entries for target
y[:10]

1     Good/Standard
2     Good/Standard
3     Good/Standard
4     Good/Standard
5     Good/Standard
6     Good/Standard
7     Good/Standard
8     Good/Standard
9     Good/Standard
11    Good/Standard
Name: target, dtype: object

In [16]:
# Encode the categorical variables using get_dummies
X = pd.get_dummies(X)
# Preview the data
X.head()

,AnnualIncome,NumBankAccounts,NumCreditCard,NumofLoan,Delayfromduedate,NumofDelayedPayment,NumCreditInquiries,OutstandingDebt,CreditUtilizationRatio,CreditHistoryAge,MonthlyBalance,CreditMix_Bad,CreditMix_Good,CreditMix_Standard
1,19114.12,3,4,4,-1,0.0,4.0,809.98,31.944960,0.0,284.629162,0,1,0
2,19114.12,3,4,4,3,7.0,4.0,809.98,28.609352,22.0,331.209863,0,1,0
3,19114.12,3,4,4,5,4.0,4.0,809.98,31.377862,22.0,223.451310,0,1,0
4,19114.12,3,4,4,6,0.0,4.0,809.98,24.797347,22.0,341.489231,0,1,0
5,19114.12,3,4,4,8,4.0,4.0,809.98,27.262259,22.0,340.479212,0,1,0

In [17]:
# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [18]:
#Check shape of X_train
X_train.shape

(59853, 14)

In [19]:
# Check shape of X_test
X_test.shape

(19952, 14)

In [20]:
# Create the StandardScaler instance
scaler = StandardScaler()
# Fit the Standard Scaler with the training data
X_scaler = scaler.fit(X_train)
# Scale the training data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
X_train_scaled

array([[-0.09042815, -0.0587721 , -0.12803877, ...,  1.78038717,
        -0.66412374, -0.9120743 ],
       [-0.10360775, -0.14438662, -0.13580123, ..., -0.56167558,
         1.5057435 , -0.9120743 ],
       [-0.1146691 ,  7.84344778, -0.11251385, ...,  1.78038717,
        -0.66412374, -0.9120743 ],
       ...,
       [-0.10358043, -0.0587721 , -0.11251385, ...,  1.78038717,
        -0.66412374, -0.9120743 ],
       [-0.09245025, -0.11014081, -0.13580123, ..., -0.56167558,
        -0.66412374,  1.0964019 ],
       [-0.11835761, -0.08445645, -0.13580123, ...,  1.78038717,
        -0.66412374, -0.9120743 ]])

In [21]:
# Instantiate the model with k = 3 neighbors
model = KNeighborsClassifier(n_neighbors=3)

In [22]:
# Train the model
model.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=3)

In [23]:
# Create predictions
y_pred = model.predict(X_test_scaled)

# Review the predictions
y_pred

array(['Poor', 'Good/Standard', 'Good/Standard', ..., 'Good/Standard',
       'Good/Standard', 'Good/Standard'], dtype=object)

In [24]:
# Print confusion matrix
confusion_matrix(y_pred,y_test)

array([[12215,  2475],
       [ 1987,  3275]])

In [25]:
# Print classification report
print(classification_report(y_pred,y_test))

               precision    recall  f1-score   support

Good/Standard       0.86      0.83      0.85     14690
         Poor       0.57      0.62      0.59      5262

     accuracy                           0.78     19952
    macro avg       0.71      0.73      0.72     19952
 weighted avg       0.78      0.78      0.78     19952